package org.agmas.noellesroles.jester;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.PlayerPoisonComponent;
import dev.doctor4t.wathe.cca.PlayerShopComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.Identifier;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.agmas.noellesroles.Noellesroles;
import org.jetbrains.annotations.NotNull;
import org.ladysnake.cca.api.v3.component.ComponentKey;
import org.ladysnake.cca.api.v3.component.ComponentRegistry;
import org.ladysnake.cca.api.v3.component.sync.AutoSyncedComponent;
import org.ladysnake.cca.api.v3.component.tick.ServerTickingComponent;

import java.util.ArrayList;
import java.util.Collections;

public class JesterPlayerComponent implements AutoSyncedComponent, ServerTickingComponent {
    public static final ComponentKey<JesterPlayerComponent> KEY = ComponentRegistry.getOrCreate(Identifier.of(Noellesroles.MOD_ID, "jester"), JesterPlayerComponent.class);
    private final PlayerEntity player;
    public int jestCount;
    public int jestRequired;
    public boolean hasBecomeKiller = false;

    // Jest Values for Jester activities
    public int jestKillPlayer = 100;
    public int jestDelusionPlayer = 3;
    public int jestDelusionUsed = 2;
    public int jestUseFirecracker = 1;
    public int jestPryDoors = 2;

    public void reset() {
        this.jestCount = 0;
        this.jestRequired = 0;
        this.hasBecomeKiller = false;
        this.sync();
    }

    public JesterPlayerComponent(PlayerEntity player) {
        this.player = player;
        jestCount = 0;
        jestRequired = 0;
    }

    public void sync() {
        KEY.sync(this.player);
    }

    public void serverTick() {
        if (!this.hasBecomeKiller && this.jestCount > 0) {
            this.notInGameReset();
            if (this.jestRequired > 0) {
                if (this.jestCount >= this.jestRequired) {
                    this.triggerBecomeKiller();
                }
            }
        }
    }

    public void notInGameReset() {
        if (GameWorldComponent.KEY.get(this.player.getWorld()).getRole(this.player) == null) {
            this.reset();
        }
    }

    public void triggerBecomeKiller() {
        GameWorldComponent gameWorld = GameWorldComponent.KEY.get(this.player.getWorld());
        if (!gameWorld.isRole(this.player, Noellesroles.JESTER) && GameFunctions.isPlayerSpectatingOrCreative(this.player)) return;
        ArrayList<Role> shuffledKillerRoles = new ArrayList<>(WatheRoles.ROLES);
        shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !role.canUseKiller() || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString()));
        if (shuffledKillerRoles.isEmpty()) shuffledKillerRoles.add(WatheRoles.KILLER);
        Collections.shuffle(shuffledKillerRoles);
        PlayerShopComponent playerShop = PlayerShopComponent.KEY.get(this.player);
        gameWorld.addRole(this.player, shuffledKillerRoles.getFirst());
        ModdedRoleAssigned.EVENT.invoker().assignModdedRole(this.player, shuffledKillerRoles.getFirst());
        playerShop.setBalance(Math.clamp(playerShop.balance, 125, 175));
        PlayerPoisonComponent.KEY.get(this.player).reset();
        if (Harpymodloader.VANNILA_ROLES.contains(gameWorld.getRole(this.player))) {
            ServerPlayNetworking.send((ServerPlayerEntity) this.player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(WatheRoles.KILLER), gameWorld.getAllKillerTeamPlayers().size(), 0));
        } else {
            ServerPlayNetworking.send((ServerPlayerEntity) this.player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(gameWorld.getRole(this.player))), gameWorld.getAllKillerTeamPlayers().size(), 0));
        }
        this.clearCounts();
    }

    public void clearCounts() {
        this.hasBecomeKiller = true;
        this.jestCount = 0;
        this.sync();
    }

    public void writeToNbt(@NotNull NbtCompound tag, RegistryWrapper.WrapperLookup registryLookup) {
        tag.putInt("jestCount", this.jestCount);
        tag.putInt("jestRequired", this.jestRequired);
    }

    public void readFromNbt(@NotNull NbtCompound tag, RegistryWrapper.WrapperLookup registryLookup) {
        this.jestCount = tag.contains("jestCount") ? tag.getInt("jestCount") : 0;
        this.jestRequired = tag.contains("jestRequired") ? tag.getInt("jestRequired") : 0;
    }
}